### ISSUE TITLE
Dataset files not found when using sample code

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis_lib#4]
Using the demo code in Readme for training, tmp_path value other than a root dir `/tmp` fails with `FileNotFoundError: [Errno 2] No such file or directory: 'tmp/dataset/tmp/dataset/abui_2_890.wav'`

This works: `tmp_path = Path('/tmp')` but anything else causes path segment to be repeated eg `tmp/dataset/tmp/dataset `

**Comment by harrykeightley** [comment]
I fixed this some recent commits. The issue was that if an absolute path was passed in as the dataset directory, it would cause the dataset audiofiles to become absolute as well, which was being handled improperly down the line. 

During dataset processing, we now just force the dataset audio files to resolve under the datset directory.
